{"uid":"a54965033226b5fe","name":"test_update_package[data0]","fullName":"TestCase.test_table.Testtable#test_update_package","historyId":"86fd89cac6e70c4da7d3c13e0fa56df0","time":{"start":1692770008459,"stop":1692770008459,"duration":0},"status":"broken","statusMessage":"TypeError: 'module' object is not callable","statusTrace":"@pytest.fixture(name='beginandend')\n    def beginToend():\n        lu = LoggerUtil()\n        logger = lu.get_logger()\n        logger.info(\"----------测试用例执行开始----------\")\n        global driver\n>       driver = webdriver.firefox()\nE       TypeError: 'module' object is not callable\n\nTestCase\\conftest.py:20: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"beginandend","time":{"start":1692770008460,"stop":1692770008473,"duration":13},"status":"broken","statusMessage":"TypeError: 'module' object is not callable\n","statusTrace":"  File \"C:\\python\\3.10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python\\3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python\\3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\UIauto\\WebUIAutoTest-master\\TestCase\\conftest.py\", line 20, in beginToend\n    driver = webdriver.firefox()\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true}],"testStage":{"status":"broken","statusMessage":"TypeError: 'module' object is not callable","statusTrace":"@pytest.fixture(name='beginandend')\n    def beginToend():\n        lu = LoggerUtil()\n        logger = lu.get_logger()\n        logger.info(\"----------测试用例执行开始----------\")\n        global driver\n>       driver = webdriver.firefox()\nE       TypeError: 'module' object is not callable\n\nTestCase\\conftest.py:20: TypeError","steps":[],"attachments":[{"uid":"6d9980c142ca9f5e","name":"log","source":"6d9980c142ca9f5e.txt","type":"text/plain","size":75}],"parameters":[],"hasContent":true,"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true},"afterStages":[],"labels":[{"name":"feature","value":"测试360搜索"},{"name":"tag","value":"@pytest.mark.usefixtures('beginandend')"},{"name":"parentSuite","value":"TestCase"},{"name":"suite","value":"test_table"},{"name":"subSuite","value":"Testtable"},{"name":"host","value":"DESKTOP-14KMC4A"},{"name":"thread","value":"30528-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"TestCase.test_table"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"data","value":"['test01', 1, '测试', '描述', '角标', 50, None]"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('beginandend')"]},"source":"a54965033226b5fe.json","parameterValues":["['test01', 1, '测试', '描述', '角标', 50, None]"]}